### ISSUE TITLE
Build failing due to ros-noetic-panda-moveit-config dependency not satisfied

### ISSUE THREAD

**Issue by ruturajsambhusvt** [ros-noetic-arch/ros-noetic-franka-ros#2]
Hello, I ran the yay -S ros-noetic-franka-ros command. The following is the error log. 

[out_fraros.log](https://github.com/ros-noetic-arch/ros-noetic-franka-ros/files/9112948/out_fraros.log)

I ran yay -S ros-noetic-panda-moveit-config and it didn't work either. The logs are attached herewith.

[out_moveit.log](https://github.com/ros-noetic-arch/ros-noetic-franka-ros/files/9112922/out_moveit.log)

**Comment by acxz** [comment]
Yep, we currently have a circular dependency with this PKGBUILD: https://github.com/ros-noetic-arch/ros-noetic-panda-moveit-config/issues/3

**Comment by acxz** [comment]
Since it is not a `makedep` you could try to install this package without checking for dependencies like so: `makepkg -d` as a workaround.

**Comment by ruturajsambhusvt** [comment]
Hello, I did that and could build subsequent packages. It looks like things are working, for now, will get back if I face any issues with these packages. Thank you very much!

**Comment by acxz** [comment]
I'm gonna close this for now, since I believe I have fixed the circular dependency. The PKGBUILD may not have all the right dependencies, however, I'll leave that for another issue.
